apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-20T10:35:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: web
    app.kubernetes.io/managed-by: Helm
    chart: web-1.0.0
    heritage: Helm
    release: rpsls-web
  name: web2
  namespace: default
  resourceVersion: "13081681"
  selfLink: /api/v1/namespaces/default/services/web2
  uid: e42be57b-e20c-430d-b4ee-104b9407053a
spec:
  clusterIP: 10.0.174.138
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32600
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
    release: rpsls-web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 51.124.70.72